[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "audio-violence-detection-tinyml"
version = "0.1.0"
description = "Audio violence detection utilities and notebooks"
requires-python = ">=3.9"
dependencies = [
    "edgeimpulse>=1.0.18",
    "ipykernel>=6.31.0",
    "matplotlib>=3.9.4",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
]

[tool.setuptools]
packages = ["scripts"]
